ZOO/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZOO.Models
{
    public class Ticket
    {
        [Key]
        public int ID { get; set; }

        public string Type { get; set; }
        public decimal? Price { get; set; }
        [DataType(DataType.Date)]
        public DateTime? AddedOn { get; set; }
        public string UpdatedBy { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public List<AttractionTicket> Attraction { get; set; }
        public List<TicketPurchase> Purchase { get; set; }
    }
}

ZOO/Models/ViewModel/TicketsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZOO.Models.ViewModel
{
    public class TicketsViewModel
    {
        public int ID { get; set; }

        public string Type { get; set; }
        public decimal? Price { get; set; }
        [DataType(DataType.Date)]
        public DateTime? AddedOn { get; set; }
        public string UpdatedBy { get; set; }
        public int? Count { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public List<AttractionTicket> Attraction { get; set; }
        public List<TicketPurchase> Purchase { get; set; }

    }
}

ZOO/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZOO.Data;
using ZOO.Models;
using ZOO.Models.ViewModel;

namespace ZOO.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TicketsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tickets.ToListAsync());
        }

        [Authorize]
        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(/*int? id*/)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var ticket = await _context.Tickets
            //    .SingleOrDefaultAsync(m => m.ID == id);
            //if (ticket == null)
            //{
            //    return NotFound();
            //}
            if (User.IsInRole("Admin"))
            {
                var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var customer = await _context.Customers.Where(a => a.ApplicationUserID == user).ToListAsync();
                if (customer.Count < 1)
                {
                    Customer cus = new Customer()
                    {
                        FirstName = "Safik",
                        LastName = "Momin",
                        PhoneNumber = "8328292659",
                        ApplicationUserID = user
                    };
                    _context.Add(cus);
                    await _context.SaveChangesAsync();
                }
            }


            ViewBag.ListCount = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 };
            ViewBag.Ticket = await _context.Tickets.ToListAsync();
            return View();
            //return View(ticket);
        }

        public async Task<IActionResult> ThankYou(List<TicketsViewModel> model)
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var customer = await _context.Customers.Where(a => a.ApplicationUserID == user).FirstAsync();
            List<TicketPurchase> AllPurchases = new List<TicketPurchase>();
            foreach (var m in model)
            {
                if (m.Count.GetValueOrDefault() > 0)
                {
                    var tix = await _context.Tickets.Where(a => a.ID == m.ID).FirstAsync();
                    decimal price = m.Price.GetValueOrDefault(0M) * m.Count.GetValueOrDefault();
                    decimal tax = price * Decimal.Parse(0.0825.ToString());
                    TicketPurchase purchase = new TicketPurchase()
                    {
                        Amount = price + tax,
                        Tax = tax,
                        PaymentType = 0,
                        Quantity = m.Count.GetValueOrDefault(),
                        Date = DateTime.Now,
                        UpdatedBy = user,
                        TicketID = m.ID,
                        CustomerID = customer.ID,
                        Customer = customer,
                        Ticket = tix
                    };
                    _context.Add(purchase);
                    await _context.SaveChangesAsync();
                    AllPurchases.Add(purchase);
                }
            }
            return View(AllPurchases);
        }

        [Authorize]
        public async Task<IActionResult> ThankYouMember()
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var customer = await _context.Customers.Where(a => a.ApplicationUserID == user).FirstAsync();
            List<TicketPurchase> AllPurchases = new List<TicketPurchase>();

            var mem = await _context.Memberships.FirstAsync();
            decimal price = mem.Price;
            decimal tax = price * Decimal.Parse(0.0825.ToString());
            TicketPurchase purchase = new TicketPurchase()
            {
                Amount = price + tax,
                Tax = tax,
                PaymentType = 0,
                Quantity = 1,
                Date = DateTime.Now,
                UpdatedBy = user,
                MembershipID = mem.ID,
                CustomerID = customer.ID,
                Customer = customer,
                Membership = mem
            };
            _context.Add(purchase);
            await _context.SaveChangesAsync();
            AllPurchases.Add(purchase);

            return View("ThankYou", AllPurchases);
        }

        // GET: Tickets/Create
        [Authorize(Roles = "Admin, Worker")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Create([Bind("ID,Type,Price,Date")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.Date = DateTime.Now;
                ticket.UpdatedBy = User.Identity.Name;
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Type,Price,Date")] Ticket ticket)
        {
            if (id != ticket.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ticket.AddedOn = DateTime.Now;
                    ticket.UpdatedBy = User.Identity.Name;
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets.SingleOrDefaultAsync(m => m.ID == id);
            _context.Tickets.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.ID == id);
        }
    }
}

ZOO/Views/Tickets/Create.cshtml
@model ZOO.Models.Ticket

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ZOO/Views/Tickets/Delete.cshtml
@model ZOO.Models.Ticket

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ZOO/Views/Tickets/Details.cshtml
@model List<ZOO.Models.ViewModel.TicketsViewModel>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout3.cshtml";
    var ticket = (List<Ticket>)ViewBag.Ticket;
}

<div class="mx-auto" id="buy-details">
    <div class="container" id="buy-body">
        <form asp-controller="Tickets" asp-action="ThankYou" method="post" role="form">
            <h2 id="ticket-buy-heading">Kalamari Zoo Admission Tickets</h2>
            <h4 id="ticket-buy-heading2">Zoo General Admission tickets are valid for 90 days from date of purchase.</h4>
            <div class="table-responsive" style="height:400px;">
                <table class="table">
                    <thead>
                        <tr></tr>
                    </thead>
                    <tbody>

                        @for (int i = 0; i < ticket.Count; i++)
                        {
                            <tr>
                                <td class="dropdown-only">
                                    <div class="dropdown">
                                        @*<select asp-for="@tix.Count" class="form-control" asp-items="@ViewBag.ListCount"></select>*@
                                        <input asp-for="@Model[i].Count" value="0" class="form-control">
                                        <input type="hidden" asp-for="@Model[i].Price" value="@ticket[i].Price" class="form-control ">
                                        <input type="hidden" asp-for="@Model[i].ID" value="@ticket[i].ID" class="form-control ">
                                    </div>
                                </td>
                                <td class="ticket-menu">
                                    <strong>@ticket[i].Type</strong>
                                    <p id="ticket-para">$@ticket[i].Price</p>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            @*<a class="btn btn-primary" role="button" asp-action="ThankYou" id="go-back-button">Buy Now<i class="fa fa-chevron-right"></i></a>*@
            <input type="submit" class="btn btn-primary" id="filter-button">
        </form>
    </div>
</div>

@*<h2>Details</h2>

    <div>
        <h4>Ticket</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

ZOO/Views/Tickets/Edit.cshtml
@model ZOO.Models.Ticket

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ZOO/Views/Tickets/Index.cshtml
@model List<ZOO.Models.Ticket>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}

<div class="mx-auto" id="ticket-details">
    <div class="container" id="ticket-details-body">
        <h1 class="text-center" id="ticket-details-heading">Buy Tickets</h1>
        <div class="row" id="ticket-body">
            <div class="col" id="ticket-col">
                <h3 id="ticket-heading">Daytime General Admission</h3>
                <ul style="color:rgb(0,0,0);font-size:20px;">
                    @foreach (var tix in Model)
                    {
                        string price = "";
                        if (tix.Price != null)
                        {
                            price = tix.Price == 0 ? "FREE" : "$"+tix.Price.ToString();
                        }
                        else
                        {
                            price = "FREE";
                        }
                        <li>@tix.Type- <strong>@price</strong></li>

                    }
                </ul>
                <p>Purchase your tickets online and skip the line at the gate! Show the digital receipt or ticket at the Online ticket line or present your Membership card at the Membership line!</p>
                <div id="button-div" class="text-center"><a class="btn btn-primary" role="button" asp-action="Details" id="go-back-button">Buy Now&nbsp;<i class="fa fa-chevron-right"></i></a></div>
            </div>
            <div class="col" id="ticket-col2">
                <h3 id="ticket-heading">Become a Member!</h3>
                <p>Members get free admission to the zoo for only <strong>$30!</strong> Become a member and enjoy free daytime admission for the entire year and many other great benefits!</p>
                <div id="button-div" class="text-center"><a class="btn btn-primary" role="button" asp-action="thankyoumember" id="go-back-button">Membership&nbsp;<i class="fa fa-chevron-right"></i></a></div>
            </div>
        </div>
    </div>
</div>

ZOO/Views/Tickets/ThankYou.cshtml
@model List<ZOO.Models.TicketPurchase>

@{
    ViewData["Title"] = "ThankYou";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}

<div class="mx-auto" id="buy-details">
    <div class="container" id="buy-body">
        <h2 id="ticket-buy-heading">Thank you for your purchase!</h2>

        <table class="table table-bordered">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr>
                        @if (m.Ticket != null)
                        {
                            <td id="report-cell">@m.Ticket.Type</td>

                        }
                        else
                        {
                            <td id="report-cell">Membership</td>

                        }
                        <td id="report-cell">@m.Quantity</td>
                        <td id="report-cell">$@Decimal.Round(m.Amount, 2)</td>
                    </tr>
                }
            </tbody>
        </table>

        <p>You purchased @Model.Sum(a => a.Quantity) Tickets/Memberships</p>
        <p>You paid $@Model.Sum(a => Decimal.Round(a.Amount,2)) including $@Model.Sum(a => Decimal.Round(a.Tax,2)) tax</p>
        <br />
        <h4 id="ticket-buy-heading2">Please check your emails for a confirmation number and use your receipt for admission or print out the ticket from your email. We hope you have a great time with our lovely animals!</h4><img src="~/assets/img/typage.jpg" id="tyimage">
    </div>
</div>