ZOO/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZOO.Data;
using ZOO.Models;
using ZOO.Models.ViewModel;

namespace ZOO.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public AnimalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Animals
        public async Task<IActionResult> Index(string Search)
        {

            //var sometext = _context.Database.SqlQuery<string>("SELECT * From Animals").ToArray();
            using (var command = _context.Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = "SELECT * From dbo.Animals";
                _context.Database.OpenConnection();
                using (SqlDataReader result = (SqlDataReader)command.ExecuteReader())
                {
                    DataTable schemaTable = result.GetSchemaTable();
                    foreach (DataRow row in schemaTable.Rows)
                    {
                        foreach (DataColumn column in schemaTable.Columns)
                        {
                            var something = String.Format("{0} = {1}", column.ColumnName, row[column]);
                        }
                    }
                    // do something with result
                }
            }
            
            if (String.IsNullOrWhiteSpace(Search))
            {
                var applicationDbContext = _context.Animals.Include(a => a.Attraction);
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.Animals.Where(a => 
                    a.Name.Contains(Search) || a.SpeciesType.Contains(Search))
                    .Include(a => a.Attraction);
                return View(await applicationDbContext.ToListAsync());
            }
            
        }

        // GET: Animals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals
                .Include(a => a.Attraction)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // GET: Animals/Create
        [Authorize(Roles ="Admin, Worker")]
        public IActionResult Create()
        {
            ViewData["AttractionID"] = new SelectList(_context.Attractions, "ID", "Name");
            ViewData["Gender"] = new SelectList(new[]
                                {
                                    new {Gender="Male"},
                                    new{Gender="Female"},
                                }, "Gender", "Gender");
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Worker")]
        //[Bind("ID,Gender,Name,SpeciesType,DOB,Vaccinated,AttractionID","AvatarImage")]
        public async Task<IActionResult> Create( Animal animal, IFormFile files)
        {
            if (ModelState.IsValid)
            {
                if (files != null)
                {

                    using (var memoryStream = new MemoryStream())
                    {
                        await files.CopyToAsync(memoryStream);
                        animal.AvatarImage = memoryStream.ToArray();
                    }
                }
                animal.AddedOn = DateTime.Now;
                animal.UpdatedBy = User.Identity.Name;
                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AttractionID"] = new SelectList(_context.Attractions, "ID", "Name", animal.AttractionID);
            ViewData["Gender"] = new SelectList(new[]
                                {
                                    new {Gender="Male"},
                                    new{Gender="Female"},
                                }, "Gender", "Gender");
            return View(animal);
        }

        // GET: Animals/Edit/5
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals.SingleOrDefaultAsync(m => m.ID == id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["Gender"] = new SelectList(new[]
                                {
                                    new {Gender="Male"},
                                    new{Gender="Female"},
                                }, "Gender", "Gender");
            ViewData["AttractionID"] = new SelectList(_context.Attractions, "ID", "Name", animal.AttractionID);
            return View(animal);
        }

        // POST: Animals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Edit(int id, Animal animal, IFormFile files)
        {
            if (id != animal.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (files != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await files.CopyToAsync(memoryStream);
                        animal.AvatarImage = memoryStream.ToArray();
                    }
                }
                
                try
                {
                    if(animal.AddedOn == null)
                    {
                        animal.AddedOn = DateTime.Now;
                    }
                    animal.UpdatedBy = User.Identity.Name;
                    _context.Update(animal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animal.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Gender"] = new SelectList(new[]
                                {
                                    new {Gender="Male"},
                                    new{Gender="Female"},
                                }, "Gender", "Gender");
            ViewData["AttractionID"] = new SelectList(_context.Attractions, "ID", "Name", animal.AttractionID);
            return View(animal);
        }

        // GET: Animals/Delete/5
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animals
                .Include(a => a.Attraction)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Worker")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var animal = await _context.Animals.SingleOrDefaultAsync(m => m.ID == id);
            _context.Animals.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnimalExists(int id)
        {
            return _context.Animals.Any(e => e.ID == id);
        }
    }
}

ZOO/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZOO.Data;

namespace ZOO.Controllers
{
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Animal(DateTime fromTime, DateTime toTime)
        {
            int x = 0;

            if (int.TryParse(fromTime.Year.ToString(), out x) && x < 2)
            {
                fromTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0);
            }
            else
            {
                fromTime = new DateTime(fromTime.Year, fromTime.Month, fromTime.Day, 0, 0, 0);
            }
            if (int.TryParse(toTime.Year.ToString(), out x) && x < 2)
            {
                toTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 23, 59, 59);
            }
            else
            {
                toTime = new DateTime(toTime.Year, toTime.Month, toTime.Day, 23, 59, 59);
            }

            ViewBag.fromTime = fromTime;
            ViewBag.toTime = toTime;

            return View(_context.Animals.Where(a => a.AddedOn >= fromTime && a.AddedOn <= toTime).ToList());
        }

        public IActionResult Ticket(DateTime fromTime, DateTime toTime)
        {
            int x = 0;

            if (int.TryParse(fromTime.Year.ToString(), out x) && x < 2)
            {
                fromTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0);
            }
            else
            {
                fromTime = new DateTime(fromTime.Year, fromTime.Month, fromTime.Day, 0, 0, 0);
            }
            if (int.TryParse(toTime.Year.ToString(), out x) && x < 2)
            {
                toTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 23, 59, 59);
            }
            else
            {
                toTime = new DateTime(toTime.Year, toTime.Month, toTime.Day, 23, 59, 59);
            }

            return View(_context.TicketPurchases.Where(t => t.Date >= fromTime && t.Date <= toTime).ToList());
        }

        public IActionResult Item(DateTime fromTime, DateTime toTime)
        {
            int x = 0;

            if (int.TryParse(fromTime.Year.ToString(), out x) && x < 2)
            {
                fromTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0);
            }
            else
            {
                fromTime = new DateTime(fromTime.Year, fromTime.Month, fromTime.Day, 0, 0, 0);
            }
            if (int.TryParse(toTime.Year.ToString(), out x) && x < 2)
            {
                toTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 23, 59, 59);
            }
            else
            {
                toTime = new DateTime(toTime.Year, toTime.Month, toTime.Day, 23, 59, 59);
            }

            return View(_context.OtherPurchases.Where(p => p.Date >= fromTime && p.Date <= toTime));
        }
    }
}

ZOO/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zoo</title>
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Adamina">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aguafina+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bahiana">
    <link rel="stylesheet" href="~/assets/css/Footer-Dark.css">
    <link rel="stylesheet" href="~/assets/css/styles.css">
</head>
<body>
    <section class="d-flex flex-column justify-content-between" id="main">
        <div id="main-top">
            <nav class="navbar navbar-light navbar-expand-md">
                <div class="container-fluid">
                    <a class="navbar-brand" id="brand" asp-area="" asp-controller="Home" asp-action="Index">Kalamari Zoo</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                         id="navcol-1" style="font-size:16px;">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" id="main-link1" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" id="main-link2" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" id="main-link3" asp-area="" asp-controller="Attractions" asp-action="Index">Exhibits</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" id="main-link4" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a></li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="main-link1" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Reports
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="Animal">Animal</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="Ticket">Financial</a>
                                </div>
                            </li>
                            @if (User != null && User.IsInRole("Admin"))
                            {

                                <li class="nav-item" role="presentation"><a class="nav-link" id="main-link4" asp-area="" asp-controller="Worker" asp-action="Index">Worker</a></li>

                            }
                        </ul>
                        @await Html.PartialAsync("_LoginPartial2")
                    </div>
                </div>
            </nav>
        </div>
        <div id="main-bot">
            <div class="container">
                @RenderBody()
            </div>
        </div>
    </section>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li>Animals</li>
                            <li>Exhibits</li>
                            <li>Tickets</li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Kalamari Zoo</h3>
                        <p class="header-para">The most exotic animal in the nation. Discover our exhibits and unique animals habits throughout the zoo. Be prepared to be entertained.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">KALAMARIZOO@2018</p>
            </div>
        </footer>
    </div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZOO/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zoo</title>
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Adamina">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aguafina+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bahiana">
    <link rel="stylesheet" href="~/assets/css/Footer-Dark.css">
    <link rel="stylesheet" href="~/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="~/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="~/assets/css/styles.css">
</head>
<body>
    <section class="d-flex flex-column justify-content-between" id="animal">
        <div id="animal-top">
            <nav class="navbar navbar-light navbar-expand-md">
                <div class="container-fluid">
                    <a class="navbar-brand" id="other-brand" asp-area="" asp-controller="Home" asp-action="Index">Kalamari Zoo</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navcol-1" style="font-size:16px;">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Attractions" asp-action="Index">Exhibits</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Reports
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="Animal">Animal</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="Ticket">Financial</a>
                                </div>
                            </li>
                            @if (User != null && User.IsInRole("Admin"))
                            {

                                <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Worker" asp-action="Index">Worker</a></li>

                            }
                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </nav>
        </div>

        @RenderBody()
        <div id="animal-bottom">
            <div class="container" id="animal-bottom-extra">
                <div class="row" id="animal-extra">
                    <div class="col-4" id="news">
                        <div class="card">
                            <h3 class="text-center" id="animal-extra-title">Animal News!</h3><img class="card-img w-100 d-block" src="~/assets/img/newsanimal.jpg">
                            <div class="card-body">
                                <p class="card-text">Find out more about the latest Zoo news on the Kalamari Zoo Blog. Get the scoop on latest animal babies, new developments, and feature creatures.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4" id="border-col">
                        <div class="card">
                            <h3 class="text-center" id="animal-extra-title">Learn More!</h3><img class="card-img w-100 d-block" src="~/assets/img/childrenanimal.jpg" id="learn" style="height:188px;">
                            <div class="card-body">
                                <p class="card-text">Want to learn more about the animals and their behavior? There are many information regarding each animals and their habitat. Let your child learn and discover more about the Zoo.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4" id="news">
                        <div class="card">
                            <h3 class="text-center" id="animal-extra-title">Saving Wildlife!</h3><img class="card-img w-100 d-block" src="~/assets/img/savinganimal.jpg" style="height:188px;">
                            <div class="card-body">
                                <p class="card-text">Help save wildlife animals by learning more about their habitats and avoiding doing harmful actions that would lead to their instinction.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li>Animals</li>
                            <li>Exhibits</li>
                            <li>Tickets</li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Kalamari Zoo</h3>
                        <p class="header-para">The most exotic animal in the nation. Discover our exhibits and unique animals habits throughout the zoo. Be prepared to be entertained.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">KALAMARIZOO@2018</p>
            </div>
        </footer>
    </div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZOO/Views/Shared/_Layout4.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zoo</title>
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Adamina">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aguafina+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bahiana">
    <link rel="stylesheet" href="~/assets/css/Footer-Dark.css">
    <link rel="stylesheet" href="~/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="~/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="~/assets/css/styles.css">
</head>
<body>
    <div class="login-dark">
        <div id="main-top">
            <nav class="navbar navbar-light navbar-expand-md">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kalamari Zoo</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                         id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Attractions" asp-action="Index">Exhibits</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a></li>
                        </ul>
                        @if (User != null && User.IsInRole("Admin"))
                        {

                            <li class="nav-item" role="presentation"><a class="nav-link" id="main-link4" asp-area="" asp-controller="Worker" asp-action="Index">Worker</a></li>

                        }
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </nav>
        </div>
        @RenderBody()
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li>Animals</li>
                            <li>Exhibits</li>
                            <li>Tickets</li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Kalamari Zoo</h3>
                        <p class="header-para">The most exotic animal in the nation. Discover our exhibits and unique animals habits throughout the zoo. Be prepared to be entertained.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">KALAMARIZOO@2018</p>
            </div>
        </footer>
    </div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZOO/Views/Shared/_LoginPartial2.cshtml
@using Microsoft.AspNetCore.Identity
@using ZOO.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item" role="presentation">
                @*<a class="nav-link" asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>*@
                <a class="nav-link" id="login-link1" asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">Account</a>
            </li>
            <li class="nav-item" role="presentation">
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="login-link1" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="login-link2" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
        </li>
    </ul>
}